/*
 * DO NOT EDIT THIS FILE! Automatically generated by SCons.
 */

#ifndef __DEBUG_TrafficGen_HH__
#define __DEBUG_TrafficGen_HH__

namespace Debug {
class SimpleFlag;
extern SimpleFlag TrafficGen;
}

#endif // __DEBUG_TrafficGen_HH__
